services:
  surve-bot-ma-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /home/vboxuser/.netrc:/home/codespace/.netrc
      - ..:/workspace:cached
    ports:
      - 5173:5173